export const QudShaderTypes = [
  "sequence",
  "pattern",
  "alternation",
  "solid",
  "bordered",
] as const;

export type QudShaderType = (typeof QudShaderTypes)[number];
export const IsQudShaderType = (s: string): s is QudShaderType => {
  return QudShaderTypes.some((t) => t === s);
};

export type QudShader = {
  name: string;
  pattern: string[];
  type: (typeof QudShaderTypes)[number];
};

export const textShaders: Record<string, QudShader> = {
  amorous: {
    name: "amorous",
    type: "alternation",
    pattern: ["r", "R", "M", "m"],
  },
  "arctic camouflage": {
    name: "arctic camouflage",
    type: "sequence",
    pattern: ["y", "y", "Y", "y", "K", "y", "y", "Y", "Y", "K"],
  },
  astral: {
    name: "astral",
    type: "alternation",
    pattern: ["Y", "y", "K", "y", "Y"],
  },
  auroral: {
    name: "auroral",
    type: "sequence",
    pattern: ["K", "g", "G", "Y", "G", "g", "K"],
  },
  bee: {
    name: "bee",
    type: "alternation",
    pattern: ["K", "w", "W", "Y", "W", "w", "K"],
  },
  beylah: {
    name: "beylah",
    type: "sequence",
    pattern: ["B", "b", "g", "k", "W", "R", "r"],
  },
  bio: {
    name: "bio",
    type: "sequence",
    pattern: ["g", "G", "W", "M", "W", "G", "g", "g", "g", "g", "g"],
  },
  biomech: {
    name: "biomech",
    type: "sequence",
    pattern: ["w", "w", "r", "r", "r", "w", "r", "r"],
  },
  blaze: {
    name: "blaze",
    type: "sequence",
    pattern: ["r", "r", "R", "W", "Y"],
  },
  brainbrine: {
    name: "brainbrine",
    type: "sequence",
    pattern: ["g", "g", "g", "w", "W", "W", "W", "w", "g", "g", "g"],
  },
  camouflage: {
    name: "camouflage",
    type: "sequence",
    pattern: ["g", "g", "G", "g", "K", "g", "g", "G", "G", "K"],
  },
  chiral: {
    name: "chiral",
    type: "sequence",
    pattern: ["B", "b", "c", "C", "M", "m", "k", "m", "M", "C", "c", "b"],
  },
  cider: {
    name: "cider",
    type: "solid",
    pattern: ["r"],
  },
  cloning: {
    name: "cloning",
    type: "sequence",
    pattern: [
      "Y",
      "Y",
      "Y",
      "Y",
      "Y",
      "Y",
      "M",
      "Y",
      "M",
      "Y",
      "Y",
      "Y",
      "Y",
      "Y",
      "Y",
    ],
  },
  cloudy: {
    name: "cloudy",
    type: "sequence",
    pattern: ["y", "y", "Y", "y", "Y", "Y"],
  },
  "coated in plasma": {
    name: "coated in plasma",
    type: "sequence",
    pattern: [
      "K",
      "K",
      "y",
      "g",
      "G",
      "Y",
      "k",
      "Y",
      "Y",
      "k",
      "Y",
      "G",
      "g",
      "y",
      "K",
      "K",
    ],
  },
  crochide: {
    name: "crochide",
    type: "sequence",
    pattern: ["g", "g", "g", "g", "g", "G"],
  },
  cryogenic: {
    name: "cryogenic",
    type: "sequence",
    pattern: ["Y", "C", "C", "Y", "c", "c", "K", "y", "Y"],
  },
  crysteel: {
    name: "crysteel",
    type: "alternation",
    pattern: ["y", "y", "K", "g", "g", "K", "y", "y"],
  },
  crystalline: {
    name: "crystalline",
    type: "sequence",
    pattern: ["m", "m", "m", "b", "B", "Y", "B", "b", "m", "m", "m"],
  },
  "dark fiery": {
    name: "dark fiery",
    type: "alternation",
    pattern: ["r", "R", "W", "R", "r"],
  },
  defoliant: {
    name: "defoliant",
    type: "sequence",
    pattern: ["W", "W", "G", "g", "K", "g", "G"],
  },
  "desert camouflage": {
    name: "desert camouflage",
    type: "sequence",
    pattern: ["w", "w", "W", "w", "K", "w", "w", "W", "W", "K"],
  },
  displacer: {
    name: "displacer",
    type: "sequence",
    pattern: ["b", "B", "Y", "B"],
  },
  dreamy: {
    name: "dreamy",
    type: "sequence",
    pattern: ["b", "b", "b", "B", "M", "k", "W", "M", "B", "b", "b", "b", "b"],
  },
  dreamsmoke: {
    name: "dreamsmoke",
    type: "sequence",
    pattern: ["b", "b", "b", "b", "y", "Y", "Y", "W", "w", "b", "b", "b"],
  },
  earth: {
    name: "earth",
    type: "sequence",
    pattern: ["b", "B", "W", "g", "G"],
  },
  extradimensional: {
    name: "extradimensional",
    type: "alternation",
    pattern: [
      "M",
      "M",
      "m",
      "m",
      "y",
      "y",
      "Y",
      "Y",
      "O",
      "Y",
      "Y",
      "y",
      "m",
      "m",
      "M",
      "M",
    ],
  },
  emote: {
    name: "emote",
    type: "solid",
    pattern: ["w"],
  },
  engraved: {
    name: "engraved",
    type: "sequence",
    pattern: ["Y", "y", "c", "C"],
  },
  eater: {
    name: "eater",
    type: "sequence",
    pattern: ["Y", "Y", "M", "Y", "Y", "Y"],
  },
  electrical: {
    name: "electrical",
    type: "sequence",
    pattern: ["W"],
  },
  entropic: {
    name: "entropic",
    type: "sequence",
    pattern: ["K", "K", "m", "K", "K", "K", "m", "m", "K", "K", "y"],
  },
  feathered: {
    name: "feathered",
    type: "alternation",
    pattern: ["C", "B", "b", "g", "G", "g", "b", "B", "C"],
  },
  fiery: {
    name: "fiery",
    type: "sequence",
    pattern: ["R"],
  },
  filthy: {
    name: "filthy",
    type: "sequence",
    pattern: ["w", "w", "K", "w", "K", "w", "W"],
  },
  forest: {
    name: "forest",
    type: "sequence",
    pattern: ["g", "g", "w", "G", "g", "g", "w", "w", "g", "G", "G", "w"],
  },
  freezing: {
    name: "freezing",
    type: "sequence",
    pattern: ["C"],
  },
  fungicide: {
    name: "fungicide",
    type: "sequence",
    pattern: ["M", "M", "R", "r", "K", "r", "R"],
  },
  gaslight: {
    name: "gaslight",
    type: "alternation",
    pattern: ["g", "g", "w", "W", "w", "g", "g"],
  },
  ghostly: {
    name: "ghostly",
    type: "alternation",
    pattern: ["Y", "Y", "y", "y", "K", "K"],
  },
  glittering: {
    name: "glittering",
    type: "sequence",
    pattern: ["K", "K", "y", "M", "y", "K", "K"],
  },
  glotrot: {
    name: "glotrot",
    type: "sequence",
    pattern: ["K", "K", "r", "R", "r"],
  },
  graffitied: {
    name: "graffitied",
    type: "sequence",
    pattern: ["R", "r", "w", "W", "Y", "y", "r", "R", "W", "w"],
  },
  "great machine": {
    name: "great machine",
    type: "sequence",
    pattern: ["c", "c", "C", "Y", "W", "k", "W", "Y", "C", "c", "c", "c", "c"],
  },
  hologram: {
    name: "hologram",
    type: "sequence",
    pattern: ["b", "B", "C", "c"],
  },
  horned: {
    name: "horned",
    type: "bordered",
    pattern: ["y", "W"],
  },
  hotkey: {
    name: "hotkey",
    type: "solid",
    pattern: ["W"],
  },
  hypertractor: {
    name: "hypertractor",
    type: "sequence",
    pattern: ["r", "R", "W", "w", "c", "C", "B", "b"],
  },
  hypervelocity: {
    name: "hypervelocity",
    type: "alternation",
    pattern: ["r", "R", "W", "Y", "W", "R", "r"],
  },
  icy: {
    name: "icy",
    type: "alternation",
    pattern: ["Y", "C", "B", "C", "Y"],
  },
  illuminated: {
    name: "illuminated",
    type: "sequence",
    pattern: ["c", "c", "c", "C", "Y", "W", "Y", "C"],
  },
  implanted: {
    name: "implanted",
    type: "sequence",
    pattern: ["r", "r", "r", "r", "r", "r", "r", "C"],
  },
  internals: {
    name: "internals",
    type: "solid",
    pattern: ["W"],
  },
  ironshank: {
    name: "ironshank",
    type: "sequence",
    pattern: ["K", "y", "Y", "y"],
  },
  issachari: {
    name: "issachari",
    type: "sequence",
    pattern: ["Y", "Y", "Y", "Y", "Y", "Y", "r"],
  },
  lacquered: {
    name: "lacquered",
    type: "sequence",
    pattern: ["Y", "y", "K", "y", "Y", "y", "K", "y", "Y", "y"],
  },
  lah: {
    name: "lah",
    type: "sequence",
    pattern: ["w", "W", "R", "r"],
  },
  lanterned: {
    name: "lanterned",
    type: "alternation",
    pattern: ["y", "y", "y", "y", "Y", "W", "Y", "y", "y"],
  },
  lava: {
    name: "lava",
    type: "solid",
    pattern: ["R"],
  },
  leafy: {
    name: "leafy",
    type: "sequence",
    pattern: ["g", "g", "G"],
  },
  leopard: {
    name: "leopard",
    type: "sequence",
    pattern: ["W", "W", "w", "w", "W", "K", "K", "w", "w", "W", "W"],
  },
  levant: {
    name: "levant",
    type: "sequence",
    pattern: ["r", "r", "y", "y", "Y", "Y"],
  },
  love: {
    name: "love",
    type: "sequence",
    pattern: ["Y", "R", "Y", "Y"],
  },
  kaleidoslug: {
    name: "kaleidoslug",
    type: "sequence",
    pattern: ["K", "C", "y", "m", "M", "r", "c", "C", "Y", "y", "K"],
  },
  kesil: {
    name: "kesil",
    type: "sequence",
    pattern: ["m", "m", "M", "Y", "y"],
  },
  metamorphic: {
    name: "metamorphic",
    type: "sequence",
    pattern: ["y", "y", "y", "Y", "Y", "Y", "M", "M", "M", "m", "m", "m", "m"],
  },
  mirrorshades: {
    name: "mirrorshades",
    type: "sequence",
    pattern: ["K", "y", "Y", "Y", "y", "K"],
  },
  jungle: {
    name: "jungle",
    type: "sequence",
    pattern: [
      "g",
      "g",
      "w",
      "G",
      "g",
      "m",
      "g",
      "w",
      "w",
      "K",
      "g",
      "m",
      "G",
      "G",
      "w",
    ],
  },
  lovesickness: {
    name: "lovesickness",
    type: "sequence",
    pattern: ["r", "R", "M", "m", "r", "R", "M"],
  },
  mercurial: {
    name: "mercurial",
    type: "alternation",
    pattern: ["c", "c", "C", "W", "Y", "W", "C", "c", "c"],
  },
  metachrome: {
    name: "metachrome",
    type: "alternation",
    pattern: ["w", "W", "Y", "C", "c", "c", "C", "Y", "W", "w"],
  },
  moon: {
    name: "moon",
    type: "sequence",
    pattern: ["b", "B", "C", "c"],
  },
  nanoneuro: {
    name: "nanoneuro",
    type: "sequence",
    pattern: ["r", "R", "G", "g", "K", "K", "g", "G", "R", "r", "g"],
  },
  nanotech: {
    name: "nanotech",
    type: "sequence",
    pattern: ["K", "K", "y", "K"],
  },
  nervous: {
    name: "nervous",
    type: "sequence",
    pattern: ["g", "g", "w", "W", "w", "g", "g"],
  },
  neutronic: {
    name: "neutronic",
    type: "sequence",
    pattern: ["B", "b", "K", "y", "Y"],
  },
  nectar: {
    name: "nectar",
    type: "sequence",
    pattern: ["W", "w", "g", "G"],
  },
  ninefold: {
    name: "ninefold",
    type: "bordered",
    pattern: ["b", "B"],
  },
  normal: {
    name: "normal",
    type: "sequence",
    pattern: ["K", "K", "y", "y", "Y", "y", "y", "K", "K", "y", "K", "y", "Y"],
  },
  normalish: {
    name: "normalish",
    type: "sequence",
    pattern: ["y", "y", "K", "y", "Y", "y", "y", "y", "K", "y", "Y"],
  },
  olive: {
    name: "olive",
    type: "sequence",
    pattern: ["g", "g", "G", "W", "w"],
  },
  opalescent: {
    name: "opalescent",
    type: "sequence",
    pattern: ["Y", "y", "K", "K", "y", "Y"],
  },
  otherpearl: {
    name: "otherpearl",
    type: "sequence",
    pattern: ["M", "m", "y", "Y", "O", "O", "Y", "y", "m", "M"],
  },
  overloaded: {
    name: "overloaded",
    type: "alternation",
    pattern: ["y", "y", "w", "W", "R", "W", "w", "y", "y"],
  },
  painted: {
    name: "painted",
    type: "sequence",
    pattern: ["r", "R", "W", "w", "g", "G", "B"],
  },
  paisley: {
    name: "paisley",
    type: "sequence",
    pattern: ["m", "M", "Y", "M", "m"],
  },
  "palladium mesh": {
    name: "palladium mesh",
    type: "sequence",
    pattern: ["c", "c", "c", "c", "C", "W", "Y", "W", "C"],
  },
  patchwork: {
    name: "patchwork",
    type: "sequence",
    pattern: ["W", "w", "r", "R", "W", "w", "b", "B", "W"],
  },
  pearly: {
    name: "pearly",
    type: "sequence",
    pattern: ["Y", "Y", "y"],
  },
  peridot: {
    name: "peridot",
    type: "sequence",
    pattern: ["G", "g", "w", "W", "Y", "W", "G"],
  },
  "phase-harmonic": {
    name: "phase-harmonic",
    type: "sequence",
    pattern: ["Y", "y", "m", "y", "K"],
  },
  plaid: {
    name: "plaid",
    type: "sequence",
    pattern: ["g", "K", "G", "W", "G"],
  },
  plasma: {
    name: "plasma",
    type: "sequence",
    pattern: ["g", "G", "Y", "Y", "G", "g"],
  },
  playernotes: {
    name: "playernotes",
    type: "solid",
    pattern: ["Y"],
  },
  plastifer: {
    name: "plastifer",
    type: "sequence",
    pattern: ["K", "y", "Y", "y"],
  },
  polarized: {
    name: "polarized",
    type: "alternation",
    pattern: ["K", "y", "Y", "y", "K", "y", "Y", "y", "K"],
  },
  prismatic: {
    name: "prismatic",
    type: "sequence",
    pattern: ["r", "R", "W", "G", "B", "b", "m"],
  },
  psionic: {
    name: "psionic",
    type: "alternation",
    pattern: ["b", "B", "C", "c", "b", "B", "C"],
  },
  psychalflesh: {
    name: "psychalflesh",
    type: "sequence",
    pattern: [
      "w",
      "w",
      "w",
      "r",
      "R",
      "M",
      "M",
      "m",
      "M",
      "M",
      "R",
      "r",
      "w",
      "w",
      "w",
      "w",
    ],
  },
  psymeridian: {
    name: "psymeridian",
    type: "sequence",
    pattern: [
      "K",
      "K",
      "y",
      "y",
      "y",
      "m",
      "M",
      "M",
      "M",
      "M",
      "m",
      "y",
      "y",
      "y",
      "K",
      "K",
    ],
  },
  putrid: {
    name: "putrid",
    type: "solid",
    pattern: ["K"],
  },
  quantumreverb: {
    name: "quantumreverb",
    type: "sequence",
    pattern: [
      "K",
      "K",
      "y",
      "Y",
      "M",
      "m",
      "O",
      "k",
      "m",
      "M",
      "Y",
      "y",
      "K",
      "K",
    ],
  },
  radiant: {
    name: "radiant",
    type: "sequence",
    pattern: ["r", "W", "Y", "Y", "Y", "W", "r"],
  },
  rainbow: {
    name: "rainbow",
    type: "alternation",
    pattern: ["r", "R", "W", "G", "B", "b", "m"],
  },
  refractive: {
    name: "refractive",
    type: "sequence",
    pattern: ["y", "Y"],
  },
  resonance: {
    name: "resonance",
    type: "alternation",
    pattern: ["c", "c", "C", "C", "W", "C", "C", "c", "c"],
  },
  rocket: {
    name: "rocket",
    type: "alternation",
    pattern: ["Y", "W", "R", "R", "r", "y"],
  },
  rubbergum: {
    name: "rubbergum",
    type: "sequence",
    pattern: ["W", "W", "w", "w", "y", "y", "Y", "W", "W"],
  },
  rules: {
    name: "rules",
    type: "solid",
    pattern: ["C"],
  },
  rusty: {
    name: "rusty",
    type: "sequence",
    pattern: ["r"],
  },
  scaled: {
    name: "scaled",
    type: "sequence",
    pattern: ["g", "G", "W", "w", "g", "G"],
  },
  snakeskin: {
    name: "snakeskin",
    type: "sequence",
    pattern: ["g", "c", "C", "G"],
  },
  shade: {
    name: "shade",
    type: "sequence",
    pattern: ["y", "K", "c", "b", "B", "y", "C", "y", "K"],
  },
  soul: {
    name: "soul",
    type: "alternation",
    pattern: ["W", "w", "c", "C", "Y", "C", "c", "w", "W"],
  },
  shemesh: {
    name: "shemesh",
    type: "sequence",
    pattern: ["r", "r", "R", "R", "W", "W", "Y"],
  },
  shimmering: {
    name: "shimmering",
    type: "sequence",
    pattern: ["Y", "Y", "y", "y", "K", "K", "y", "y"],
  },
  sickly: {
    name: "sickly",
    type: "sequence",
    pattern: ["g", "r", "m", "w", "K", "G", "g", "c", "K"],
  },
  silvery: {
    name: "silvery",
    type: "sequence",
    pattern: ["Y"],
  },
  skulk: {
    name: "skulk",
    type: "sequence",
    pattern: ["b", "b", "B", "b", "b"],
  },
  slimy: {
    name: "slimy",
    type: "solid",
    pattern: ["g"],
  },
  "snail-encrusted": {
    name: "snail-encrusted",
    type: "sequence",
    pattern: ["w", "W", "Y", "y"],
  },
  sparkling: {
    name: "sparkling",
    type: "sequence",
    pattern: ["y", "y", "Y"],
  },
  spaser: {
    name: "spaser",
    type: "sequence",
    pattern: ["K", "g", "G", "G", "g", "K"],
  },
  spiked: {
    name: "spiked",
    type: "bordered",
    pattern: ["R", "Y"],
  },
  "spring-turret": {
    name: "spring-turret",
    type: "sequence",
    pattern: ["c", "c", "C", "C", "y", "y", "y", "y", "y", "C", "C", "c", "c"],
  },
  sphynx: {
    name: "sphynx",
    type: "sequence",
    pattern: ["C", "c", "m", "M"],
  },
  starry: {
    name: "starry",
    type: "sequence",
    pattern: ["K", "Y", "K", "K", "Y", "K"],
  },
  structural: {
    name: "structural",
    type: "alternation",
    pattern: ["Y", "y", "K", "y", "Y"],
  },
  sun: {
    name: "sun",
    type: "alternation",
    pattern: ["W", "R", "W"],
  },
  sunslag: {
    name: "sunslag",
    type: "sequence",
    pattern: ["r", "W", "Y", "Y", "Y", "W", "r"],
  },
  sunset: {
    name: "sunset",
    type: "alternation",
    pattern: [
      "b",
      "B",
      "B",
      "M",
      "m",
      "r",
      "R",
      "W",
      "C",
      "C",
      "W",
      "R",
      "r",
      "m",
      "M",
      "B",
      "B",
      "b",
    ],
  },
  syphon: {
    name: "syphon",
    type: "sequence",
    pattern: ["c", "c", "c", "C", "W", "Y"],
  },
  tarnished: {
    name: "tarnished",
    type: "sequence",
    pattern: ["G", "G", "g"],
  },
  tartan: {
    name: "tartan",
    type: "sequence",
    pattern: ["y", "K", "g", "G", "K", "R", "r", "K", "y"],
  },
  telemetric: {
    name: "telemetric",
    type: "alternation",
    pattern: ["K", "y", "c", "C", "Y", "W", "C", "c", "y", "K"],
  },
  thermo: {
    name: "thermo",
    type: "sequence",
    pattern: ["R", "R", "r", "c", "b", "B", "B"],
  },
  transkinetic: {
    name: "transkinetic",
    type: "sequence",
    pattern: ["Y", "C", "C", "c", "y", "K", "K", "y", "R", "W", "W", "Y"],
  },
  turbow: {
    name: "turbow",
    type: "sequence",
    pattern: ["K", "y", "Y", "Y", "R", "r"],
  },
  ubernostrum: {
    name: "ubernostrum",
    type: "sequence",
    pattern: ["c", "g", "G", "W", "w", "c", "C", "G", "g", "w", "W"],
  },
  "urban camouflage": {
    name: "urban camouflage",
    type: "sequence",
    pattern: ["y", "y", "K", "y", "K", "y", "y", "K", "y", "K"],
  },
  visage: {
    name: "visage",
    type: "sequence",
    pattern: ["R", "r", "b", "B", "Y", "y"],
  },
  watery: {
    name: "watery",
    type: "alternation",
    pattern: ["B", "C", "Y", "C", "B"],
  },
  ydfreehold: {
    name: "ydfreehold",
    type: "sequence",
    pattern: ["r", "R", "k", "c", "C", "W", "W", "C", "c", "r", "R"],
  },
  zetachrome: {
    name: "zetachrome",
    type: "alternation",
    pattern: ["m", "M", "Y", "C", "c", "c", "C", "Y", "M", "m"],
  },
  agolgot: {
    name: "agolgot",
    type: "sequence",
    pattern: ["K", "g", "w", "m", "w", "g", "K"],
  },
  bethsaida: {
    name: "bethsaida",
    type: "sequence",
    pattern: ["w", "W", "C", "c", "m", "c", "C", "W", "w"],
  },
  rermadon: {
    name: "rermadon",
    type: "sequence",
    pattern: ["Y", "G", "g", "m", "m", "g", "G", "Y"],
  },
  shugruith: {
    name: "shugruith",
    type: "sequence",
    pattern: ["K", "y", "W", "w", "m", "w", "W", "y", "K"],
  },
  qas: {
    name: "qas",
    type: "sequence",
    pattern: ["C", "c", "m"],
  },
  qon: {
    name: "qon",
    type: "sequence",
    pattern: ["m", "b", "B"],
  },
  ehalcodon: {
    name: "ehalcodon",
    type: "sequence", 
    pattern: ["y", "y", "Y", "Y", "m", "Y", "Y", "y", "y"],
  },
};
